# Generated by Django 5.2 on 2025-04-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('location', models.CharField(max_length=200, verbose_name='Emplacement')),
                ('camera_type', models.CharField(choices=[('USB', 'USB Camera'), ('IP', 'IP Camera'), ('RTSP', 'RTSP Stream')], max_length=50, verbose_name='Type')),
                ('source', models.CharField(help_text='Numéro de périphérique (0, 1, etc.) ou URL RTSP', max_length=500, verbose_name='Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
