# Generated by Django 5.2 on 2025-05-13 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_department_userprofile_recognitionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='label_id',
            new_name='face_label',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
