# Generated by Django 5.2 on 2025-05-13 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_label_id_userprofile_face_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrolled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
